# Configuration defaults - override with environment variables
server:
  address: ":8080"
  environment: "dev"

health_check:
  interval: "2s"

strategy:
  type: "weighted-round-robin"
  virtual_nodes: 200

backends:
  - url: "http://localhost:8081"
    weight: 1
  - url: "http://localhost:8082"
    weight: 1
  - url: "http://localhost:8083"
    weight: 1
  - url: "http://localhost:8084"
    weight: 1
  - url: "http://localhost:8085"
    weight: 1

logging:
  level: "debug"
